FOOD_ID_COL = 0
NAME_COL = 1
PRICE_COL = 2
MIN_COL = 3
MAX_COL = 4
TARGET_COL = 5

FOOD_ID_COL_WIDTH = 0
NAME_COL_WIDTH = 1
PRICE_COL_WIDTH = 50
MIN_COL_WIDTH = 3
MAX_COL_WIDTH = 4
TARGET_COL_WIDTH = 5

F_COLS_TO_HIDE = [FOOD_ID_COL, MIN_COL, MAX_COL, TARGET_COL]
C_COLS_TO_HIDE = [FOOD_ID_COL, PRICE_COL]

FRIDGE_V_HEADER_SIZE = 32

col_to_attr = {FOOD_ID_COL: 'food_id', NAME_COL: 'name', PRICE_COL: 'price',
               MIN_COL: 'min', MAX_COL: 'max', TARGET_COL: 'target'}


NUT_NAME_COL = 0
NUT_AMOUNT_COL = 1
NUT_UNIT_COL = 2
NUT_PERCENT_COL = 3

NUT_NAME_COL_WIDTH = 100
NUT_AMOUNT_COL_WIDTH = 50
NUT_UNIT_COL_WIDTH = 40
NUT_PERCENT_COL_WIDTH = 130

NUT_V_HEADER_SIZE = 22

NUT_COL_WIDTHS = [NUT_NAME_COL_WIDTH, NUT_AMOUNT_COL_WIDTH, NUT_UNIT_COL_WIDTH, NUT_PERCENT_COL_WIDTH]

COL_TO_NUT_ATTR = {NUT_NAME_COL: 'name', NUT_AMOUNT_COL: 'amount', NUT_UNIT_COL: 'unit',
                    NUT_PERCENT_COL: 'percent'}


OPT_NAME_COL = 0
OPT_PRICE_COL = 1
OPT_QUANTITY_COL= 2