# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow_tab.ui',
# licensing of 'ui_mainwindow_tab.ui' applies.
#
# Created: Wed Jul 24 16:15:23 2019
#      by: pyside2-uic  running on PySide2 5.13.0a1.dev1556284177
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 702)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon_trimmed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(18, 18))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.search_tab = QtWidgets.QWidget()
        self.search_tab.setObjectName("search_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.search_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.search_btn = QtWidgets.QPushButton(self.search_tab)
        self.search_btn.setObjectName("search_btn")
        self.gridLayout.addWidget(self.search_btn, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.search_box = QtWidgets.QLineEdit(self.search_tab)
        self.search_box.setInputMask("")
        self.search_box.setText("")
        self.search_box.setPlaceholderText("")
        self.search_box.setObjectName("search_box")
        self.gridLayout.addWidget(self.search_box, 0, 1, 1, 2)
        self.search_list = QtWidgets.QListWidget(self.search_tab)
        self.search_list.setAlternatingRowColors(True)
        self.search_list.setObjectName("search_list")
        self.gridLayout.addWidget(self.search_list, 1, 1, 1, 4)
        self.add_custom_food_btn = QtWidgets.QPushButton(self.search_tab)
        self.add_custom_food_btn.setObjectName("add_custom_food_btn")
        self.gridLayout.addWidget(self.add_custom_food_btn, 4, 1, 1, 1)
        self.add_to_fridge_btn = QtWidgets.QPushButton(self.search_tab)
        self.add_to_fridge_btn.setObjectName("add_to_fridge_btn")
        self.gridLayout.addWidget(self.add_to_fridge_btn, 4, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.search_tab, icon1, "")
        self.fridge_tab = QtWidgets.QWidget()
        self.fridge_tab.setObjectName("fridge_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.fridge_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fridge_table = QtWidgets.QTableWidget(self.fridge_tab)
        self.fridge_table.setAlternatingRowColors(True)
        self.fridge_table.setShowGrid(False)
        self.fridge_table.setGridStyle(QtCore.Qt.SolidLine)
        self.fridge_table.setRowCount(0)
        self.fridge_table.setColumnCount(5)
        self.fridge_table.setObjectName("fridge_table")
        self.fridge_table.setColumnCount(5)
        self.fridge_table.setRowCount(0)
        self.fridge_table.horizontalHeader().setVisible(False)
        self.fridge_table.horizontalHeader().setCascadingSectionResizes(False)
        self.fridge_table.horizontalHeader().setHighlightSections(False)
        self.fridge_table.horizontalHeader().setSortIndicatorShown(True)
        self.fridge_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.fridge_table)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.remove_btn = QtWidgets.QPushButton(self.fridge_tab)
        self.remove_btn.setObjectName("remove_btn")
        self.gridLayout_2.addWidget(self.remove_btn, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("fridge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.fridge_tab, icon2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nutrition_table = QtWidgets.QTableWidget(self.centralwidget)
        self.nutrition_table.setMinimumSize(QtCore.QSize(300, 0))
        self.nutrition_table.setColumnCount(3)
        self.nutrition_table.setObjectName("nutrition_table")
        self.nutrition_table.setColumnCount(3)
        self.nutrition_table.setRowCount(0)
        self.nutrition_table.horizontalHeader().setCascadingSectionResizes(False)
        self.nutrition_table.horizontalHeader().setStretchLastSection(False)
        self.nutrition_table.verticalHeader().setVisible(False)
        self.nutrition_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.nutrition_table)
        self.optimize_btn = QtWidgets.QPushButton(self.centralwidget)
        self.optimize_btn.setObjectName("optimize_btn")
        self.verticalLayout_2.addWidget(self.optimize_btn)
        self.debug_btn = QtWidgets.QPushButton(self.centralwidget)
        self.debug_btn.setObjectName("debug_btn")
        self.verticalLayout_2.addWidget(self.debug_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Spartan", None, -1))
        self.search_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Search", None, -1))
        self.add_custom_food_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Add custom food", None, -1))
        self.add_to_fridge_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Add to Fridge", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search_tab), QtWidgets.QApplication.translate("MainWindow", "Search", None, -1))
        self.remove_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Remove food", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fridge_tab), QtWidgets.QApplication.translate("MainWindow", "Fridge", None, -1))
        self.optimize_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Optimize Diet", None, -1))
        self.debug_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Debug", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))

