# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_requirementswindow.ui',
# licensing of 'ui_requirementswindow.ui' applies.
#
# Created: Wed Sep  4 21:48:41 2019
#      by: pyside2-uic  running on PySide2 5.13.0a1.dev1556284177
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_RequirementsWindow(object):
    def setupUi(self, RequirementsWindow):
        RequirementsWindow.setObjectName("RequirementsWindow")
        RequirementsWindow.resize(982, 719)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        RequirementsWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        RequirementsWindow.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(RequirementsWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(RequirementsWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setMargin(0)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(RequirementsWindow)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 5)
        self.label_4 = QtWidgets.QLabel(RequirementsWindow)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.mon_edit = QtWidgets.QLineEdit(RequirementsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mon_edit.sizePolicy().hasHeightForWidth())
        self.mon_edit.setSizePolicy(sizePolicy)
        self.mon_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.mon_edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mon_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.mon_edit.setObjectName("mon_edit")
        self.gridLayout.addWidget(self.mon_edit, 3, 1, 1, 1)
        self.day_edit = QtWidgets.QLineEdit(RequirementsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.day_edit.sizePolicy().hasHeightForWidth())
        self.day_edit.setSizePolicy(sizePolicy)
        self.day_edit.setMaximumSize(QtCore.QSize(50, 21))
        self.day_edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.day_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.day_edit.setObjectName("day_edit")
        self.gridLayout.addWidget(self.day_edit, 3, 2, 1, 1)
        self.year_edit = QtWidgets.QLineEdit(RequirementsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_edit.sizePolicy().hasHeightForWidth())
        self.year_edit.setSizePolicy(sizePolicy)
        self.year_edit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.year_edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.year_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.year_edit.setObjectName("year_edit")
        self.gridLayout.addWidget(self.year_edit, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(RequirementsWindow)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 5, 1, 1)
        self.sex_edit = QtWidgets.QComboBox(RequirementsWindow)
        self.sex_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sex_edit.sizePolicy().hasHeightForWidth())
        self.sex_edit.setSizePolicy(sizePolicy)
        self.sex_edit.setMinimumSize(QtCore.QSize(130, 0))
        self.sex_edit.setObjectName("sex_edit")
        self.sex_edit.addItem("")
        self.sex_edit.addItem("")
        self.sex_edit.addItem("")
        self.sex_edit.addItem("")
        self.gridLayout.addWidget(self.sex_edit, 3, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(RequirementsWindow)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 8, 1, 1)
        self.req_edit = QtWidgets.QComboBox(RequirementsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.req_edit.sizePolicy().hasHeightForWidth())
        self.req_edit.setSizePolicy(sizePolicy)
        self.req_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.req_edit.setObjectName("req_edit")
        self.req_edit.addItem("")
        self.gridLayout.addWidget(self.req_edit, 3, 9, 1, 1)
        self.cust_edit = QtWidgets.QCheckBox(RequirementsWindow)
        self.cust_edit.setObjectName("cust_edit")
        self.gridLayout.addWidget(self.cust_edit, 5, 0, 1, 3)
        self.debug_btn = QtWidgets.QPushButton(RequirementsWindow)
        self.debug_btn.setObjectName("debug_btn")
        self.gridLayout.addWidget(self.debug_btn, 5, 6, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(RequirementsWindow)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 10, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.macro_view = QtWidgets.QTableView(RequirementsWindow)
        self.macro_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.macro_view.setShowGrid(False)
        self.macro_view.setObjectName("macro_view")
        self.macro_view.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.macro_view)
        self.vit_view = QtWidgets.QTableView(RequirementsWindow)
        self.vit_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vit_view.setShowGrid(False)
        self.vit_view.setObjectName("vit_view")
        self.vit_view.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.vit_view)
        self.mineral_view = QtWidgets.QTableView(RequirementsWindow)
        self.mineral_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mineral_view.setShowGrid(False)
        self.mineral_view.setObjectName("mineral_view")
        self.mineral_view.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.mineral_view)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 11)

        self.retranslateUi(RequirementsWindow)
        QtCore.QMetaObject.connectSlotsByName(RequirementsWindow)
        RequirementsWindow.setTabOrder(self.mon_edit, self.day_edit)
        RequirementsWindow.setTabOrder(self.day_edit, self.year_edit)
        RequirementsWindow.setTabOrder(self.year_edit, self.cust_edit)
        RequirementsWindow.setTabOrder(self.cust_edit, self.macro_view)
        RequirementsWindow.setTabOrder(self.macro_view, self.debug_btn)

    def retranslateUi(self, RequirementsWindow):
        RequirementsWindow.setWindowTitle(QtWidgets.QApplication.translate("RequirementsWindow", "Dialog", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Nutritional Requirements", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Set requirements according to national guidelines", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Birthdate", None, -1))
        self.mon_edit.setPlaceholderText(QtWidgets.QApplication.translate("RequirementsWindow", "Month", None, -1))
        self.day_edit.setPlaceholderText(QtWidgets.QApplication.translate("RequirementsWindow", "Day", None, -1))
        self.year_edit.setPlaceholderText(QtWidgets.QApplication.translate("RequirementsWindow", "Year", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Sex", None, -1))
        self.sex_edit.setItemText(0, QtWidgets.QApplication.translate("RequirementsWindow", "Female", None, -1))
        self.sex_edit.setItemText(1, QtWidgets.QApplication.translate("RequirementsWindow", "Female, lactating", None, -1))
        self.sex_edit.setItemText(2, QtWidgets.QApplication.translate("RequirementsWindow", "Female, pregnant", None, -1))
        self.sex_edit.setItemText(3, QtWidgets.QApplication.translate("RequirementsWindow", "Male", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Recommendations by", None, -1))
        self.req_edit.setItemText(0, QtWidgets.QApplication.translate("RequirementsWindow", "USDA", None, -1))
        self.cust_edit.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Allow custom requirements", None, -1))
        self.debug_btn.setText(QtWidgets.QApplication.translate("RequirementsWindow", "debug", None, -1))

