# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_requirementswindow.ui',
# licensing of 'ui_requirementswindow.ui' applies.
#
# Created: Fri Sep 13 20:17:22 2019
#      by: pyside2-uic  running on PySide2 5.13.0a1.dev1556284177
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_RequirementsWindow(object):
    def setupUi(self, RequirementsWindow):
        RequirementsWindow.setObjectName("RequirementsWindow")
        RequirementsWindow.resize(1000, 780)
        RequirementsWindow.setMaximumSize(QtCore.QSize(1600, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        RequirementsWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        RequirementsWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon_trimmed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RequirementsWindow.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(RequirementsWindow)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(RequirementsWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(18)
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setMargin(0)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(RequirementsWindow)
        self.label_4.setMaximumSize(QtCore.QSize(20, 20))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/person-outline.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(RequirementsWindow)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.req_label = QtWidgets.QLabel(RequirementsWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.req_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.req_label.setFont(font)
        self.req_label.setObjectName("req_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.req_label)
        self.req_edit = QtWidgets.QComboBox(RequirementsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.req_edit.sizePolicy().hasHeightForWidth())
        self.req_edit.setSizePolicy(sizePolicy)
        self.req_edit.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.req_edit.setFont(font)
        self.req_edit.setMouseTracking(False)
        self.req_edit.setFocusPolicy(QtCore.Qt.TabFocus)
        self.req_edit.setStyleSheet("QComboBox {\n"
"    padding: 2px 0px 2px 2px;\n"
"}\n"
"\n"
"QListView{\n"
"    outline: none;\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    color: black;\n"
"    background-color: rgb(204, 232, 255);\n"
"}\n"
"\n"
"QListView::item {\n"
"    min-height: 28px;\n"
"}\n"
"")
        self.req_edit.setFrame(True)
        self.req_edit.setObjectName("req_edit")
        self.req_edit.addItem("")
        self.req_edit.addItem("")
        self.req_edit.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.req_edit)
        self.sex_label = QtWidgets.QLabel(RequirementsWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.sex_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.sex_label.setFont(font)
        self.sex_label.setObjectName("sex_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sex_label)
        self.sex_edit = QtWidgets.QComboBox(RequirementsWindow)
        self.sex_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sex_edit.sizePolicy().hasHeightForWidth())
        self.sex_edit.setSizePolicy(sizePolicy)
        self.sex_edit.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.sex_edit.setFont(font)
        self.sex_edit.setFocusPolicy(QtCore.Qt.TabFocus)
        self.sex_edit.setStyleSheet("QComboBox {\n"
"    padding: 2px 0px 2px 2px;\n"
"}\n"
"\n"
"QListView{\n"
"    outline: none;\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    color: black;\n"
"    background-color: rgb(204, 232, 255);\n"
"}\n"
"\n"
"QListView::item {\n"
"    min-height: 28px;\n"
"}\n"
"")
        self.sex_edit.setObjectName("sex_edit")
        self.sex_edit.addItem("")
        self.sex_edit.addItem("")
        self.sex_edit.addItem("")
        self.sex_edit.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sex_edit)
        self.birth_label = QtWidgets.QLabel(RequirementsWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.birth_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.birth_label.setFont(font)
        self.birth_label.setObjectName("birth_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.birth_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mon_edit = QtWidgets.QLineEdit(RequirementsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mon_edit.sizePolicy().hasHeightForWidth())
        self.mon_edit.setSizePolicy(sizePolicy)
        self.mon_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.mon_edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mon_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.mon_edit.setObjectName("mon_edit")
        self.horizontalLayout_4.addWidget(self.mon_edit)
        self.day_edit = QtWidgets.QLineEdit(RequirementsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.day_edit.sizePolicy().hasHeightForWidth())
        self.day_edit.setSizePolicy(sizePolicy)
        self.day_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.day_edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.day_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.day_edit.setObjectName("day_edit")
        self.horizontalLayout_4.addWidget(self.day_edit)
        self.year_edit = QtWidgets.QLineEdit(RequirementsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_edit.sizePolicy().hasHeightForWidth())
        self.year_edit.setSizePolicy(sizePolicy)
        self.year_edit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.year_edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.year_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.year_edit.setObjectName("year_edit")
        self.horizontalLayout_4.addWidget(self.year_edit)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(RequirementsWindow)
        self.label_5.setMaximumSize(QtCore.QSize(20, 20))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("images/info-outline.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(RequirementsWindow)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.cust_edit = QtWidgets.QCheckBox(RequirementsWindow)
        self.cust_edit.setObjectName("cust_edit")
        self.verticalLayout_2.addWidget(self.cust_edit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.macro_view = QtWidgets.QTableView(RequirementsWindow)
        self.macro_view.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.macro_view.setFont(font)
        self.macro_view.setFocusPolicy(QtCore.Qt.NoFocus)
        self.macro_view.setStyleSheet("QHeaderView::section{\n"
"    background-color: white;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QTableView {\n"
"    alternate-background-color: rgb(247, 247, 247);\n"
"}")
        self.macro_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.macro_view.setAlternatingRowColors(True)
        self.macro_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.macro_view.setShowGrid(False)
        self.macro_view.setObjectName("macro_view")
        self.macro_view.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.macro_view)
        self.vit_view = QtWidgets.QTableView(RequirementsWindow)
        self.vit_view.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.vit_view.setFont(font)
        self.vit_view.setFocusPolicy(QtCore.Qt.NoFocus)
        self.vit_view.setStyleSheet("QHeaderView::section{\n"
"    background-color: white;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QTableView {\n"
"    alternate-background-color: rgb(247, 247, 247);\n"
"}")
        self.vit_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vit_view.setAlternatingRowColors(True)
        self.vit_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.vit_view.setShowGrid(False)
        self.vit_view.setObjectName("vit_view")
        self.vit_view.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.vit_view)
        self.mineral_view = QtWidgets.QTableView(RequirementsWindow)
        self.mineral_view.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.mineral_view.setFont(font)
        self.mineral_view.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mineral_view.setStyleSheet("QHeaderView::section{\n"
"    background-color: white;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QTableView {\n"
"    alternate-background-color: rgb(247, 247, 247);\n"
"}")
        self.mineral_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mineral_view.setAlternatingRowColors(True)
        self.mineral_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.mineral_view.setShowGrid(False)
        self.mineral_view.setObjectName("mineral_view")
        self.mineral_view.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.mineral_view)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(RequirementsWindow)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(RequirementsWindow)
        QtCore.QMetaObject.connectSlotsByName(RequirementsWindow)
        RequirementsWindow.setTabOrder(self.req_edit, self.sex_edit)
        RequirementsWindow.setTabOrder(self.sex_edit, self.mon_edit)
        RequirementsWindow.setTabOrder(self.mon_edit, self.day_edit)
        RequirementsWindow.setTabOrder(self.day_edit, self.year_edit)
        RequirementsWindow.setTabOrder(self.year_edit, self.cust_edit)

    def retranslateUi(self, RequirementsWindow):
        RequirementsWindow.setWindowTitle(QtWidgets.QApplication.translate("RequirementsWindow", "Nutritional Requirements", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Nutritional Requirements", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Set requirements according to national recommendations.", None, -1))
        self.req_label.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Recommendation by", None, -1))
        self.req_edit.setCurrentText(QtWidgets.QApplication.translate("RequirementsWindow", "United States (Health Department)", None, -1))
        self.req_edit.setItemText(0, QtWidgets.QApplication.translate("RequirementsWindow", "United States (Health Department)", None, -1))
        self.req_edit.setItemText(1, QtWidgets.QApplication.translate("RequirementsWindow", "European Union (Food Safety Authority)", None, -1))
        self.req_edit.setItemText(2, QtWidgets.QApplication.translate("RequirementsWindow", "Japan (Ministry of Health, Labour and Welfare)", None, -1))
        self.sex_label.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Sex", None, -1))
        self.sex_edit.setItemText(0, QtWidgets.QApplication.translate("RequirementsWindow", "Female", None, -1))
        self.sex_edit.setItemText(1, QtWidgets.QApplication.translate("RequirementsWindow", "Female, lactating", None, -1))
        self.sex_edit.setItemText(2, QtWidgets.QApplication.translate("RequirementsWindow", "Female, pregnant", None, -1))
        self.sex_edit.setItemText(3, QtWidgets.QApplication.translate("RequirementsWindow", "Male", None, -1))
        self.birth_label.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Date of birth", None, -1))
        self.mon_edit.setPlaceholderText(QtWidgets.QApplication.translate("RequirementsWindow", "Month", None, -1))
        self.day_edit.setPlaceholderText(QtWidgets.QApplication.translate("RequirementsWindow", "Day", None, -1))
        self.year_edit.setPlaceholderText(QtWidgets.QApplication.translate("RequirementsWindow", "Year", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("RequirementsWindow", "You can select a recommendation as a guideline then customize it to your needs.", None, -1))
        self.cust_edit.setText(QtWidgets.QApplication.translate("RequirementsWindow", "Allow custom requirements", None, -1))

